SET SERVEROUTPUT ON;

ACCEPT PROMT_UNIVERSITY_NAME CHAR PROMPT 'Введите название университета: ';
ACCEPT PROMT_UNIVERSITY_RATING NUMBER PROMPT 'Введите рейтинг университета: ';
ACCEPT PROMT_UNIVERSITY_CITY CHAR PROMPT 'Введите город, где находится универтитет: ';

CREATE TABLE UNIVERSITY_LAB_5 (
    UNIV_ID INTEGER PRIMARY KEY,
    UNIV_NAME CHAR(140) NOT NULL UNIQUE,
    RATING INTEGER,
    CITY CHAR(30) NOT NULL
);

-- DROP SEQUENCE UNIV_ID_SEQUENCE
-- CREATE SEQUENCE UNIV_ID_SEQUENCE START WITH 1;

-- DELETE FROM UNIVERSITY_LAB_5 WHERE UNIV_ID > 0;

BEGIN
    INSERT INTO UNIVERSITY_LAB_5 VALUES (
        UNIV_ID_SEQUENCE.NEXTVAL,
        '&PROMT_UNIVERSITY_NAME',
        &PROMT_UNIVERSITY_RATING,
        '&PROMT_UNIVERSITY_CITY'
    );
    DBMS_OUTPUT.PUT_LINE('Запись успешно добавлена.');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Ошибка: Уникальное значение нарушено. Проверьте название университета.');
END;
/